name: build-and-publish-cross-platform

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'quay.io/pypa/manylinux_2_28_x86_64' || null }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ["3.13", "3.14"]
        package: [pycork] #, pyvoro, pybullet]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        if: runner.os != 'Linux'
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        if: runner.os != 'Linux'
        run: python -m pip install pyyaml build numpy cmake cython scikit_build_core wheel setuptools

      - name: PYTHON Variable (Linux)
        if: runner.os == 'Linux'
        run: |
          PYD=${{ matrix.python-version }}
          PY=${PYD//./}
          PYTHON=/opt/python/cp${PY}-cp${PY}/bin/python
          echo "PYTHON=$PYTHON" >> "$GITHUB_ENV" 

      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run:
          $PYTHON -m pip install pyyaml build numpy cmake cython scikit_build_core wheel setuptools

      - name: Clone external repo
        if: runner.os != 'Linux'
        run: |
          REPO=$(python scripts/load_config.py ${{ matrix.package }} repo)
          REF=$(python scripts/load_config.py ${{ matrix.package }} ref)

          git clone --recursive $REPO packages/${{ matrix.package }}/repo
          cd packages/${{ matrix.package }}/repo
          git checkout $REF

      - name: Clone external repo (Linux)
        if: runner.os == 'Linux'
        run: |
          REPO=$($PYTHON scripts/load_config.py ${{ matrix.package }} repo)
          REF=$($PYTHON scripts/load_config.py ${{ matrix.package }} ref)

          git clone --recursive $REPO packages/${{ matrix.package }}/repo
          cd packages/${{ matrix.package }}/repo
          git checkout $REF

      # ---------- Linux deps ----------
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          dnf install -y gmp-devel

      # ---------- macOS deps ----------
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install automake autoconf libtool
          vcpkg install gmp:x64-osx
          
      # ---------- Windows deps ----------
      #- name: Install Windows dependencies
      #  if: runner.os == 'Windows'
      #  run: |
      #    choco install cmake -y

      - name: Build arm64 wheel (macOS)
        if: runner.os == 'macOS'
        env:
          ARCHFLAGS: "-arch arm64"
          CMAKE_OSX_ARCHITECTURES: "arm64"
          CMAKE_OSX_DEPLOYMENT_TARGET: "10.12"
          CMAKE_ARGS: "-DCYTHONIZE=ON"
        run: |
          cd packages/${{ matrix.package }}/repo
          CMAKE_BUILD_DIR=build-arm64 CFLAGS="-fno-define-target-os-macros" python -m build --wheel --no-isolation

      - name: Build x64 wheel (macOS)
        if: runner.os == 'macOS'
        env:
          ARCHFLAGS: "-arch x86_64"
          CMAKE_OSX_ARCHITECTURES: "x86_64"
          VCPKG_TARGET_TRIPLET: "x64-osx"
          CMAKE_OSX_DEPLOYMENT_TARGET: "10.12"
          CMAKE_ARGS: "-DCYTHONIZE=ON"
          CMAKE_TOOLCHAIN_FILE: /usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          PKG_CONFIG_LIBDIR: /usr/local/share/vcpkg/installed/x64-osx/lib/pkgconfig
        run: |
          cd packages/${{ matrix.package }}/repo
          CMAKE_BUILD_DIR=build-x64 CFLAGS="-fno-define-target-os-macros" python -m build --wheel --no-isolation

      - name: Build wheel (Windows)
        if: runner.os == 'Windows'
        env:
          CMAKE_ARGS: "-DCYTHONIZE=ON"
        run: |
          cd packages/${{ matrix.package }}/repo
          python -m build --wheel --no-isolation

      - name: Build in manylinux container
        if: runner.os == 'Linux'
        env:
          CMAKE_ARGS: "-DCYTHONIZE=ON"
        run: |
          cd /packages/${{ matrix.package }}/repo"
          $PYTHON -m build --wheel --no-isolation
          auditwheel repair dist/*.whl -w wheelhouse/

      - name: Upload wheels (manylinux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.package }}
          path: packages/${{ matrix.package }}/repo/wheelhouse/*.whl

      - name: Upload wheels
        if: runner.os != 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.package }}
          path: packages/${{ matrix.package }}/repo/dist/*.whl

  assemble:

    needs: build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: all_wheels

      - name: Flatten artifacts
        run: |
          mkdir merged
          find all_wheels -name "*.whl" -exec cp {} merged/ \;

      - name: Build registry
        run: |
          mkdir -p all_wheels
          cp merged/*.whl all_wheels/

          python scripts/build_registry.py
          python scripts/build_index.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:

    needs: assemble
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - id: deployment
        uses: actions/deploy-pages@v4
