name: build-and-publish-cross-platform

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]
        python-version: ["3.13"]
        package: [pycork]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pyyaml
        run: pip install pyyaml

      - name: Clone external repo
        run: |
          REPO=$(python scripts/load_config.py ${{ matrix.package }} repo)
          REF=$(python scripts/load_config.py ${{ matrix.package }} ref)

          git clone --recursive $REPO packages/${{ matrix.package }}/repo
          cd packages/${{ matrix.package }}/repo
          git checkout $REF

      - name: Install build tools
        run: pip install build numpy cmake cython scikit_build_core wheel setuptools

     # ---------- Linux deps ----------
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          vcpkg install gmp:x64-linux

      # ---------- macOS deps ----------
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install automake autoconf libtool
          vcpkg install gmp:x64-osx gmp:arm64-osx
          
      # ---------- Windows deps ----------
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          vcpkg install gmp:x64-windows

      - name: Build arm64 wheel (macOS)
        if: runner.os == 'macOS'
        env:
          ARCHFLAGS: "-arch arm64"
          CMAKE_OSX_ARCHITECTURES: "arm64"
          VCPKG_TARGET_TRIPLET: "arm64-osx"
          CMAKE_OSX_DEPLOYMENT_TARGET: "10.12"
          CMAKE_ARGS: "-DCYTHONIZE=ON"
        run: |
          cd packages/${{ matrix.package }}/repo
          CMAKE_BUILD_DIR=build-arm64 CFLAGS="-fno-define-target-os-macros" python -m build --wheel --no-isolation

      - name: Build x64 wheel (macOS)
        if: runner.os == 'macOS'
        env:
          ARCHFLAGS: "-arch x86_64"
          CMAKE_OSX_ARCHITECTURES: "x86_64"
          VCPKG_TARGET_TRIPLET: "x64-osx"
          CMAKE_OSX_DEPLOYMENT_TARGET: "10.12"
          CMAKE_ARGS: "-DCYTHONIZE=ON"
        run: |
          cd packages/${{ matrix.package }}/repo
          CMAKE_BUILD_DIR=build-x64 CFLAGS="-fno-define-target-os-macros" python -m build --wheel --no-isolation

      - name: Build wheel (other OS)
        if: runner.os != 'macOS'
        env:
          CMAKE_ARGS: "-DCYTHONIZE=ON"
        run: |
          cd packages/${{ matrix.package }}/repo
          python -m build --wheel --no-isolation

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.package }}
          path: packages/${{ matrix.package }}/repo/dist/*.whl

  assemble:

    needs: build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: all_wheels

      - name: Flatten artifacts
        run: |
          mkdir merged
          find all_wheels -name "*.whl" -exec cp {} merged/ \;

      - name: Build registry
        run: |
          mkdir -p all_wheels
          cp merged/*.whl all_wheels/

          python scripts/build_registry.py
          python scripts/build_index.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:

    needs: assemble
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - id: deployment
        uses: actions/deploy-pages@v4
